[HPRO-1318] Group samples/orders based upon when they're made.
all-of-us/healthpro pull request #1285
Opened 2023-01-23 16:33 UTC by Ehaic

| Q                   | A
| ------------------- | --------------
| Target Release?     | 3.0.0 
| Bug fix?            | ❌ 
| New feature?        | ❌ 
| Database migration? | ✅ 
| New configuration?  | ❌ 
| Composer updates?   | ❌ 
| NPM updates?        | ❌ 
| Jira Ticket(s)      | HPRO-1318 

### Summary

### Instructions for testing  

### Screenshots

2023-01-23 19:05 UTC, shyamzcode commented
@Ehaic Could you also fix phpstan errors?

2023-01-23 19:38 UTC, shyamzcode commented
@Ehaic Noticed in the participant summary page it's displaying multiple orders for the same timepoint blood samples.

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/6041980/214133398-a091319c-4322-48eb-960a-4e8cadf4ad60.png">

2023-01-23 20:20 UTC, Ehaic commented
> @Ehaic Noticed in the participant summary page it's displaying duplicate orders for the same timepoint blood samples.
> 
> <img alt="image" width="1279" src="https://user-images.githubusercontent.com/6041980/214133398-a091319c-4322-48eb-960a-4e8cadf4ad60.png">

Good catch, I changed `templates/program/nph/order/samples.html.twig` because I found another bug testing these changes that made it so those row's only printed out if the first sample in a particular timepoint was created. I'll make more changes to that loop to fix it.

2023-01-23 22:15 UTC, thornview requested changes

2023-01-23 22:15 UTC, thornview commented on migrations/Version20230118144015.php
> +        // this down() migration is auto-generated, please modify it to your needs
Another comment to remove. 
```suggestion
```

2023-01-23 22:15 UTC, thornview commented on migrations/Version20230118144015.php
> + */
Remove auto-generated comments

```suggestion
```

2023-01-23 22:15 UTC, thornview commented on src/Controller/NphOrderController.php
> +            'samplesStatus' => $nphOrderService->getSamplesWithStatus(),
Unnecessary trailing comma
```suggestion
            'samplesStatus' => $nphOrderService->getSamplesWithStatus()
```

2023-01-23 22:15 UTC, thornview commented on src/Controller/NphPDFController.php
> +        $OrderPDF = $PDF->batchPDF($nphOrderService->getParticipantOrderSummaryByModuleVisitAndSampleGroup($participantId, $module, $visit, $sampleGroup)['order'], $nphParticipantSummaryService->getP
It's hard to read the logic when the parameters span multiple lines.  Break this into separate lines to make it easier to read. 

```suggestion
        $OrderPDF = $PDF->batchPDF($nphOrderService->
            getParticipantOrderSummaryByModuleVisitAndSampleGroup(
                $participantId, 
                $module, 
                $visit,
                $sampleGroup)['order'],
                $nphParticipantSummaryService->getParticipantById($participantId), 
                $module, 
                $visit
        );
```

2023-01-23 22:15 UTC, thornview commented on src/Entity/NphOrder.php
> +        return '';
It seems odd to return an empty string.  Would this work if the function returned null?

2023-01-23 22:15 UTC, thornview commented on src/Repository/NphOrderRepository.php
> +    public function getOrdersBySampleGroup($participantId, $sampleGroup)
Type-hint these parameters and provide a return type.  Also, this new public method should have a related test.

2023-01-23 22:15 UTC, thornview commented on src/Service/Nph/NphOrderService.php
> +    public function getParticipantOrderSummaryByModuleVisitAndSampleGroup(
New public method should have a test.

2023-01-23 22:15 UTC, thornview commented on src/Service/Nph/NphOrderService.php
> +    }
This method should also have tests, which will probably need some mocks.

2023-01-25 16:23 UTC, shyamzcode approved these changes

2023-01-25 16:45 UTC, merged