[HPRO-1182] Added NPH Participant Review Pages and Tests.
all-of-us/healthpro pull request #1314
Opened 2023-02-07 15:02 UTC by Ehaic

| Q                   | A
| ------------------- | --------------
| Target Release?     | 3.0.0 
| Bug fix?            | ❌ 
| New feature?        | ✅ 
| Database migration? | ❌ 
| New configuration?  | ❌ 
| Composer updates?   | ❌ 
| NPM updates?        | ❌ 
| Jira Ticket(s)      | HPRO-1182

### Summary

### Instructions for testing  

### Screenshots

2023-02-07 22:14 UTC, shyamzcode commented
I think in todays participant page we need to display unique participants. Participant ids and name should be grouped together like in the AOU Today's participant page

![image](https://user-images.githubusercontent.com/6041980/217378700-83450b29-eadd-4208-9288-d922c3c39480.png)

AOU Today's participant page
![image](https://user-images.githubusercontent.com/6041980/217378882-e7225bfe-d9db-45ca-aa8e-2797cd5d3744.png)

2023-02-07 22:20 UTC, shyamzcode commented
Looks like the search is not working as expected. When I enter today's date and submit I get empty results even though there are participants.
![image](https://user-images.githubusercontent.com/6041980/217379783-19fa64f5-7b72-4329-af99-8a951004d78b.png)

2023-02-07 22:21 UTC, shyamzcode commented on templates/program/nph/review/today.html.twig
> +                <a href="{{ path('review_today') }}" class="btn btn-default">Reset</a>
This should redirect to nph_review_today route.

2023-02-07 22:25 UTC, shyamzcode requested changes
I commented few things that I noticed. Rest looks good.

2023-02-08 15:51 UTC, Ehaic commented
> I think in todays participant page we need to display unique participants. Participant ids and name should be grouped together like in the AOU Today's participant page
> 
> ![image](https://user-images.githubusercontent.com/6041980/217378700-83450b29-eadd-4208-9288-d922c3c39480.png)
> 
> AOU Today's participant page ![image](https://user-images.githubusercontent.com/6041980/217378882-e7225bfe-d9db-45ca-aa8e-2797cd5d3744.png)

This is how the mockup show's it, things are grouped by the order not the participant. https://www.figma.com/file/BxLo0kukva3gdj2T0AD60V/NPH?node-id=1588%3A8779

2023-02-14 15:35 UTC, shyamzcode commented on migrations/Version20230210142836.php
> + */
Could you remove these auto generated comments?

2023-02-14 16:32 UTC, shyamzcode requested changes
Left a comment regarding the auto generated comments. Rest looks good!

2023-02-15 18:29 UTC, shyamzcode commented on migrations/Version20230210142836.php
> +        // this down() migration is auto-generated, please modify it to your needs
@Ehaic Could you remove this as well?

2023-02-15 20:55 UTC, shyamzcode approved these changes

2023-02-15 20:56 UTC, merged