[HPRO-1654] 24 Hour Urine color, clarity, and Total Collection Volume
all-of-us/healthpro pull request #1623
Opened 2023-11-14 19:32 UTC by Ehaic

| Q                   | A
| ------------------- | --------------
| Target Release?     | 4.1.0 
| Bug fix?            | ❌ 
| New feature?        | ✅ 
| Database migration? | ❌ 
| New configuration?  | ❌ 
| Composer updates?   | ❌ 
| NPM updates?        | ❌ 
| Jira Ticket(s)      | HPRO-1654 

### Summary

### Instructions for testing  

### Screenshots

2023-11-15 17:50 UTC, shyamzcode approved these changes

2023-11-16 19:17 UTC, thornview requested changes

2023-11-16 19:17 UTC, thornview commented on src/Form/Nph/NphSampleFinalizeType.php
> +        if ($orderType === NphOrder::TYPE_URINE | $orderType === NPHOrder::TYPE_24URINE) {
```suggestion
        if ($orderType === NphOrder::TYPE_URINE || $orderType === NPHOrder::TYPE_24URINE) {
```

2023-11-16 19:17 UTC, thornview commented on src/Service/Nph/NphOrderService.php
> +                        if ($order->getOrderType() === NphOrder::TYPE_URINE || $order->getOrderType() === NphOrder::TYPE_24URINE) {
Please update any related tests.

2023-11-22 17:44 UTC, shyamzcode approved these changes

2023-11-22 18:29 UTC, thornview approved these changes

2023-11-22 19:07 UTC, merged