[HPRO-1815][HPRO-1840][HPRO-1826] Added auto update modifications fix clearing measurements
all-of-us/healthpro pull request #1742
Opened 2024-03-08 15:31 UTC by Ehaic

| Q                   | A
| ------------------- | --------------
| Target Release?     | Next available 
| Bug fix?            | ❌ 
| New feature?        | ✅ 
| Database migration? | ❌ 
| New configuration?  | ❌ 
| Composer updates?   | ❌ 
| NPM updates?        | ❌ 
| Jira Ticket(s)      | HPRO-1815,HPRO-1840,HPRO-1826 

### Summary

### Instructions for testing  

### Screenshots

2024-03-08 16:39 UTC, shyamzcode requested changes
1815, Looks like you missed the "Apply modification to all readings" check box to enable/disable this auto modification feature.
1826, I still see the growth percentile being displayed even after clearing out the weight/height fields. I couldn't locate the part of the code responsible for clearing the percentile. Is it included in the PR?

2024-03-08 17:52 UTC, Ehaic commented
> 1815, Looks like you missed the "Apply modification to all readings" check box to enable/disable this auto modification feature. 1826, I still see the growth percentile being displayed even after clearing out the weight/height fields. I couldn't locate the part of the code responsible for clearing the percentile. Is it included in the PR?

The only one that wasn't clearing for me was BMI percentile, and I did miss that I pushed it with this [commit ](https://github.com/all-of-us/healthpro/pull/1742/commits/6543d5d189ab031f9c27b40347dd006c89753d96)

2024-03-08 19:40 UTC, shyamzcode commented
> > 1815, Looks like you missed the "Apply modification to all readings" check box to enable/disable this auto modification feature. 1826, I still see the growth percentile being displayed even after clearing out the weight/height fields. I couldn't locate the part of the code responsible for clearing the percentile. Is it included in the PR?
> 
> The only one that wasn't clearing for me was BMI percentile, and I did miss that I pushed it with this [commit ](https://github.com/all-of-us/healthpro/pull/1742/commits/6543d5d189ab031f9c27b40347dd006c89753d96)

@Ehaic It looks like the auto modification apply is only working for the weight field but not for other fields like height/length, waist circumference, etc. Also, the BMI percentile doesn't seem to clear out for me even when I removed the weight/height fields. Is it working for you?

2024-03-11 15:08 UTC, shyamzcode approved these changes

2024-03-11 18:21 UTC, merged