[HPRO-767] Migrate participant details to Symfony
all-of-us/healthpro pull request #825
Opened 2021-02-19 17:49 UTC by shyamnaru

| Q                   | A
| ------------------- | --------------
| Target Release?     | Next available 
| Bug fix?            | ❌ 
| New feature?        | ❌ 
| Database migration? | ❌ 
| New configuration?  | ❌ 
| Composer updates?   | ❌ 
| NPM updates?        | ❌ 
| Jira Ticket(s)      | HPRO-767

2021-02-24 22:10 UTC, jt2k approved these changes

2021-02-25 17:57 UTC, stephenyeargin requested changes
Dug into the double button issue.

2021-02-25 17:57 UTC, stephenyeargin commented on symfony/templates/participant/details.html.twig
> +                            <button type="submit" class="btn btn-success">Acknowledge</button>
This results in a duplicate "Acknowledge" button. To make this work, we likely need to do something like:

```
{{ form_start(agreeForm) }}
{{ form_widget(agreeForm.Acknowledge) }}
<a href="{{ path(cancelRoute) }}" class="btn btn-default">Cancel</a>
{{ form_end(agreeForm) }}

```

2021-02-26 16:32 UTC, stephenyeargin approved these changes

2021-02-26 16:33 UTC, merged