[HPRO-811] Adjust flash messages on Sites admin
all-of-us/healthpro pull request #876
Opened 2021-05-18 19:26 UTC by stephenyeargin

| Q                   | A
| ------------------- | --------------
| Target Release?     | Next available 
| Bug fix?            | ✅ 
| New feature?        | ❌ 
| Database migration? | ❌ 
| New configuration?  | ❌ 
| Composer updates?   | ❌ 
| NPM updates?        | ❌ 
| Jira Ticket(s)      | HPRO-811 

### Summary

Trivial fix to align the flash messages for the Sites management tool (were inadvertently left as the ones for Page Notices).

2021-05-18 22:47 UTC, jt2k requested changes

2021-05-18 22:47 UTC, jt2k commented on symfony/src/Controller/SitesController.php
> +                throw $this->createNotFoundException('Site not found.');
Can you change this to something like `Sites cannot be created when RDR sync is enabled.` as requested in the ticket?

2021-05-18 22:47 UTC, jt2k commented on symfony/src/Controller/SitesController.php
> +                    $this->addFlash('success', 'Site added.');
Should be `Site updated.`

2021-05-18 23:39 UTC, stephenyeargin commented on symfony/src/Controller/SitesController.php
> +                throw $this->createNotFoundException('Sites cannot be created when the RDR Awardee API is enabled.');
Gave it a formal name to match the one we use in the cron job.

https://github.com/all-of-us/healthpro/blob/c486539f864213ff961dccafdf1895e6965e0141/symfony/src/Controller/CronController.php#L37-L38

2021-05-19 14:13 UTC, jt2k approved these changes

2021-05-19 14:19 UTC, shyamnaru approved these changes

2021-05-19 14:28 UTC, merged