[HPRO-856] Build the Functionality and Navigation to let Managers Add and Remove Members from the Google Groups within the Managed Access Dashboard
all-of-us/healthpro pull request #918
Opened 2021-07-26 16:30 UTC by shyamnaru

| Q                   | A
| ------------------- | --------------
| Target Release?     | Next available 
| Bug fix?            | ❌ 
| New feature?        | ✅ 
| Database migration? | ❌ 
| New configuration?  | ❌ 
| Composer updates?   | ❌ 
| NPM updates?        | ❌ 
| Jira Ticket(s)      | HPRO-856

2021-07-29 19:03 UTC, shyamnaru commented on dev_config/config.yml.dist
> +# feature.managegrouppilotsites:
Handled in https://github.com/all-of-us/healthpro/pull/919 PR

2021-08-03 21:32 UTC, jt2k requested changes
Looks good overall! Just a couple notes on handling API call errors.

2021-08-03 21:32 UTC, jt2k commented on symfony/src/Controller/AccessManagementController.php
> +    }
👍

2021-08-03 21:32 UTC, jt2k commented on symfony/src/Controller/AccessManagementController.php
> +                    ]);
I'm not sure we want to return the error message to the user. In the `removeMember` method, you are catching an API exception and returning the message. That may contain information that we don't want to display and/or could be confusing. I think a generic messsage could be added to the flash message, and then we can add the result message to the log object.

2021-08-03 21:32 UTC, jt2k commented on symfony/src/Controller/AccessManagementController.php
> +                ]);
Same as below. Can we return a generic error message to the user, and then add the return the result message to the log object?

2021-08-06 15:02 UTC, jt2k approved these changes

2021-08-06 15:14 UTC, merged