[HPRO-890] Cleanup composer.json file and update dependencies
all-of-us/healthpro pull request #989
Opened 2021-11-15 16:47 UTC by shyamnaru

| Q                   | A
| ------------------- | --------------
| Target Release?     | Next available 
| Bug fix?            | ❌ 
| New feature?        | ❌ 
| Database migration? | ❌ 
| New configuration?  | ❌ 
| Composer updates?   | ✅/
| NPM updates?        | ❌ 
| Jira Ticket(s)      | HPRO-890

2021-11-15 17:11 UTC, stephenyeargin approved these changes

2021-11-15 17:12 UTC, jt2k commented on composer.lock
> +            "version": "1.26.1",
The Symfony monolog bundle was downgraded from 5.x to 4.4, which is what we want. But a side effect of this is a major version downgrade for monolog. We should check to make sure this doesn't have any unintended side effects.

2021-11-15 17:12 UTC, jt2k commented on composer.lock
> -                    "Google_": "src/"
I think we have a number of places where we are still using the old PSR-0 `Google_`... class names. I guess the aliases file makes this backwards compatible? Can you confirm that all of our Google client functionality that is using the underscore separated global class names still works?

2021-11-15 23:03 UTC, jt2k requested changes

2021-11-15 23:03 UTC, jt2k commented on composer.json
> +        "symfony/web-profiler-bundle": "^4.4"
Same with these, too.

2021-11-16 16:05 UTC, jt2k approved these changes

2021-11-16 16:20 UTC, stephenyeargin approved these changes

2021-11-17 15:34 UTC, merged